apiVersion: v1
kind: ConfigMap
metadata:
  name: app-config
  namespace: cloud-manager
  labels:
    app.kubernetes.io/name: cloud-manager
    app.kubernetes.io/component: config
data:
  AWS_REGION: "us-east-1"
  PORT: "8080"
  GIN_MODE: "release"
  IAM_ORG_ROLE_NAME: "IAMManagerCrossAccountRole"