apiVersion: v1
kind: Service
metadata:
  name: cloud-manager
  namespace: cloud-manager
  labels:
    app.kubernetes.io/name: cloud-manager
    app.kubernetes.io/component: app
spec:
  ports:
  - port: 8080
    targetPort: 8080
    protocol: TCP
    name: http
  selector:
    app.kubernetes.io/name: cloud-manager
    app.kubernetes.io/component: app
  type: ClusterIP