apiVersion: v1
kind: Service
metadata:
  name: aws-iam-manager
  namespace: aws-iam-manager
  labels:
    app.kubernetes.io/name: aws-iam-manager
    app.kubernetes.io/component: app
spec:
  ports:
  - port: 8080
    targetPort: 8080
    protocol: TCP
    name: http
  selector:
    app.kubernetes.io/name: aws-iam-manager
    app.kubernetes.io/component: app
  type: ClusterIP